name: svrn
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.1
  - scikit-learn=1.5.1
  - matplotlib=3.9.1
  - seaborn=0.13.2
  - networkx=3.3
  - tqdm=4.66.4
  - pytorch=2.3.1
  - pytorch-cuda=12.1        # omit / adjust if running on CPU only
  - pip:
      - torch-geometric==2.5.3
      - pytorch-lightning==2.3.3
      - scanpy==1.10.2
      - anndata==0.10.8
      - scikit-misc==0.3.1
